Add JLink support
01org/CODK-A pull request #25
Opened 2016-12-28 00:11 UTC by calvinatintel

Need https://github.com/01org/CODK-A-Flashpack/pull/8 on flashpack directory to test

2017-02-02 00:22 UTC, eriknyquist requested changes
uploading x86 works, arc fails. Come see me for details.

2017-02-27 18:59 UTC, calvinatintel commented
ARC side fixed. Please review.

2017-03-03 00:43 UTC, eriknyquist approved these changes

2017-03-03 01:01 UTC, eriknyquist commented
Verified

2017-03-03 01:11 UTC, merged